---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: Ensure Apache2 is started and enabled
  service:
     name: apache2
     state: started
     enabled: yes

- name: Install firewalld
  apt:
    name: firewalld
    state: present

- name: Ensure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open HTTP port (80)
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded      

